---
branches:
  only:
  - source
language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.name "Naydenov Anatoly"
- git config --global user.email "a@naydenov.tk"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- bundle exec rake setup_github_pages[$REPO_URL]
script:
- bundle exec rake generate
after_script:
- bundle exec rake deploy
env:
  global:
  - GH_REPO="a-naydenov/a-naydenov.github.com"
  - secure: "KsA1J8L40ebXKN9SCciM4QmX1JvuIQPHt0VEwW+TVdYN/I6mdOT83Val8Ld8S/MvgUt58AXi1GzGSD0EtuQBfEwRoeRPgDTZIOz65s4LYilI+XWvF/t8fNMutNejs0mrk6fWyOAVbGNvNm+ZEsJ/TU8/xMoDbqHBhSwX3fV4vAE="
  - secure: "AKLWIo8VxaliMlMjaF1nwlDgQMPXzDLhdHH2NBrLL7AdglXledQiIU62ELMOn9KFBiU+yxO3MT9tlDvyH1YGZ6wWaM9+xS1SbrTEWdT0OT3FDvFlmQtweHgkmuw6V/PUs1DMR7LiR4XlvJdllPgOJcGR+A5U9w9J36YxYSty7EM="