# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://a-naydenov.github.com
enforce_ssl: article.naydenov.tk

title: Блог Найдёнова Анатолия
subtitle: 
author: Найдёнов Анатолий
# description: Персональный блог Найденова Анатолия
keywords: найденов анатолий, блог, иркутск

date_format: "ordinal"

subscribe_rss: /atom.xml
# subscribe_email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

root: /
permalink: /:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 3          # Posts per page on the blog index
pagination_dir:  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Дальше &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

emoji_dir: /images/emoji


#linklog
permalink_label: "&#9875;"
permalink_label_feed: "&#9875;"
linklog_marker:
linklog_marker_position:
linklog_marker_position_feed:
standard_post_marker: "&#9875;"
# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

twitter:
  consumer_key: NHMPI2BiREV4xVIEar7RvUjUo
  consumer_secret: rFFPnagzoHjbk3IhvhunLiQnx71I8vUS47iCWlkXJVfuct5cAP
  access_token: 1052585036-1wEPv6LAcoFxOpx751K9ASQ3KBHGDsquAeRmdDu
  access_token_secret: RhOxq6pp94KS3MO36kX0SfVMN0Xu2hH2lwEDFJk2X2OAe


# Google Analytics
google_analytics_tracking_id: UA-34488886-1


#prose.io settings 
prose:
  rooturl: "source"
  metadata:
    "source/_posts":
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          value: "Title"
      - name: "comments"
        field:
          label: "Allow comments"
          element: "checkbox"
          value: true
      - name: "categories"
        field:
          element: "text"
          value: "misc"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: true
      - name: "sharing"
        field:
          label: "sharing"
          element: "checkbox"
          value: false
      - name: "description"
        field:
          element: "text"
          value: "description"
      - name: "cover"
        field:
          element: "text"
          value: "cover"
